### ISSUE TITLE
Cannot load project in Intellig IDEA due to missing .iml files

### ISSUE THREAD

**Issue by medboz** [JetBrains/teamcity-investigations-auto-assigner#14]
Hello,
I'm trying to load the last version of the project in Intellig IDEA Community(2018.1.5) but got these errors:

11:11	Error Loading Project: Cannot load 3 modules Details...

1. Investigations-auto-assigner. Cannot load module file 'D:/ARD/git/teamcity-investigations-auto-assigner/.idea/modules/investigations/investigations-auto-assigner.iml': File D:\ARD\git\teamcity-investigations-auto-assigner\.idea\modules\investigations-auto-assigner.iml does not exist

2. Investigations-auto-assigner. Cannot load module file 'D:/ARD/git/teamcity-investigations-auto-assigner/.idea/modules/investigations/investigations-auto-assigner_test.iml': File D:\ARD\git\teamcity-investigations-auto-assigner\.idea\modules\investigations-auto-assigner_test.iml does not exist 

3. Investigations-auto-assigner. Cannot load module file 'D:/ARD/git/teamcity-investigations-auto-assigner/.idea/modules/investigations/investigations-auto-assigner_main.iml': File D:\ARD\git\teamcity-investigations-auto-assigner\.idea\modules\investigations-auto-assigner_main.iml does not exist 

Can you please help me fix this?

**Comment by rugpanov** [comment]
Please check out the [ build](https://teamcity.jetbrains.com/viewLog.html?buildId=1497681&buildTypeId=TeamCityPluginsByJetBrains_InvestigationsAutoAssigner_BuildAgainstTeamCity81x). When you are opening the repository in Idea you can select the "Import Gradle project" option.

**Comment by medboz** [comment]
Thank you @rugpanov  I will try It
