### ISSUE TITLE
Error when downloading dependencies from external repositories(Sorry I'm not experienced with Intellig IDEA and Gradle)

### ISSUE THREAD

**Issue by medboz** [JetBrains/teamcity-investigations-auto-assigner#15]
I tried to add proxy config in gradle.properties and in Itellig IDEA settings but still gettings this error:

> NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
> NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
> NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'investigations-auto-assigner'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not resolve com.github.rodm:gradle-teamcity-plugin:1.1.
>      Required by:
>          project :
>       > Could not resolve com.github.rodm:gradle-teamcity-plugin:1.1.
>          > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'.
>             > Could not GET 'https://repo.maven.apache.org/maven2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'. Received status code 407 from server: authenticationrequired
>       > Could not resolve com.github.rodm:gradle-teamcity-plugin:1.1.
>          > Could not get resource 'https://plugins.gradle.org/m2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'.
>             > Could not GET 'https://plugins.gradle.org/m2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'. Received status code 407 from server: authenticationrequired
>       > Could not resolve com.github.rodm:gradle-teamcity-plugin:1.1.
>          > Could not get resource 'https://jcenter.bintray.com/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'.
>             > Could not GET 'https://jcenter.bintray.com/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'. Received status code 407 from server: authenticationrequired
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> CONFIGURE FAILED in 0s
> Could not GET 'https://repo.maven.apache.org/maven2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'. Received status code 407 from server: authenticationrequired
> Enable Gradle 'offline mode' and sync project
> 

Can you please advice on how to fix this ?

**Comment by rugpanov** [comment]
@medboz, hi! First of all, it isn't a problem of the project, but the problem of your proxy configuration. Have you tried to [configure a proxy](https://stackoverflow.com/questions/5991194/gradle-proxy-configuration) with all these suggestions?

**Comment by medboz** [comment]
Hello @rugpanov,

I get the error bellow when I set proxy properties in gradle.properties or when I run [gradlew --info -Dhttps.proxyHost={Company Proxy} -Dhttps.proxyPort=8080 -Dhttps.proxyUser={my login} -Dhttps.proxyPassword={my password}](url), I get this error : 

> Evaluating root project 'investigations-auto-assigner' using build file 'D:\ARD\git\teamcity-investigations-auto-assigner\build.gradle'.
> NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
> Failed to get resource: GET. [HTTP HTTP/1.1 407 authenticationrequired: https://repo.maven.apache.org/maven2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom]
> **_NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
> Failed to get resource: GET. [HTTP HTTP/1.1 407 authenticationrequired: https://plugins.gradle.org/m2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom]_**
> NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
> Failed to get resource: GET. [HTTP HTTP/1.1 407 authenticationrequired: https://jcenter.bintray.com/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom]
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'investigations-auto-assigner'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not resolve com.github.rodm:gradle-teamcity-plugin:1.1.
>      Required by:
>          project :
>       > Could not resolve com.github.rodm:gradle-teamcity-plugin:1.1.
>          > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'.
>             > Could not GET 'https://repo.maven.apache.org/maven2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'. Received status code 407 from server: authenticationrequired
>       > Could not resolve com.github.rodm:gradle-teamcity-plugin:1.1.
>          > Could not get resource 'https://plugins.gradle.org/m2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'.
>             > Could not GET 'https://plugins.gradle.org/m2/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'. Received status code 407 from server: authenticationrequired
>       > Could not resolve com.github.rodm:gradle-teamcity-plugin:1.1.
>          > Could not get resource 'https://jcenter.bintray.com/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'.
>             > Could not GET 'https://jcenter.bintray.com/com/github/rodm/gradle-teamcity-plugin/1.1/gradle-teamcity-plugin-1.1.pom'. Received status code 407 from server: authenticationrequired
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

Any idea?

**Comment by medboz** [comment]
It seems gradle doesn't work properly with  ntlm proxy. As a workaround, I'm using [cntlm ](http://cntlm.sourceforge.net/) as local proxy in the middle (gradle <=> cntlm local proxy <=> company ntlm proxy

**Comment by medboz** [comment]
@rugpanov: don't know what could be the next issue :)
