### ISSUE TITLE
Logging is very minimal

### ISSUE THREAD

**Issue by Sharken03** [JetBrains/teamcity-investigations-auto-assigner#20]
One of the ongoing challenges is finding out how the plugin made a decision regarding who broke the build.
To get that information in the server log requires debugging, but practically all of the debug log is useful in the day to day operation.

It would be great to be able to configure an option in the plugin, which will redirect debug output to the teamcity serverlog by way of the Logger.info() method.

**Comment by rugpanov** [comment]
@Sharken03 , hi! I suppose the correct approach is to add a new logging preset for auto-assigner. For my purpose I used smt like:
```
  <category name="jetbrains.buildServer.iaa" additivity="false">
    <priority value="DEBUG" />
    <appender-ref ref="AUTO_ASSIGNER.LOG" />
  </category>
```
...
```
  <appender name="AUTO_ASSIGNER.LOG" class="jetbrains.buildServer.util.TCRollingFileAppender">
    <param name="file" value="${teamcity_logs}/teamcity-auto-assigner.log" />
    <param name="maxBackupIndex" value="3" />
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern" value="[%d] %6p - %30.30c - %m %n" />
    </layout>
  </appender>
```
If this approach doesn't work for you, please could you provide more details about your case.

**Comment by medboz** [comment]
This what I've done to investigate some issues I encountered in our Teamcity server.

**Comment by rugpanov** [comment]
@Sharken03 , any updates?

**Comment by Sharken03** [comment]
@rugpanov 
Yes, i can report that the above works just fine. I opted to add it to the conf\teamcity-server-log4j.xml configuration file, so we always get a separate logfile for the auto assigner.
