### ISSUE TITLE
Add information on the wiki on how to modify DEFAULT_PROCESSING_DELAY_IN_SECONDS

### ISSUE THREAD

**Issue by Sharken03** [JetBrains/teamcity-investigations-auto-assigner#22]
The situation is that the plugin by default checks every two minutes if a build has new errors that can be assigned. It would be nice to change that, as builds can take several hours to complete, and it is not needed to check up on the build every two minutes.

Have modified Internal Properties but it is not clear if a server restart is also needed.

**Comment by Sharken03** [comment]
Excellent, thank you!

**Comment by rugpanov** [comment]
@Sharken03, thank you for you suggestion.
