### ISSUE TITLE
Reasoning behind the error text "Probably broke the build.." is hard to understand

### ISSUE THREAD

**Issue by Sharken03** [JetBrains/teamcity-investigations-auto-assigner#32]
We have just had the plugin assign someone to a broken build, where the text was set to "Investigation was automatically assigned to "username" who changed suspicious file ".build-profile" which probably broke the build."

Looking at the code, this error text comes from the BrokenFileHeuristic.java file, where processing is being done on the _problemText_ variable.
For us the error above makes no sense, so it would be nice if you could print the value of _problemText_, if it was used to fail the build.

Another possibility could be that the filename ".build-profile' somehow triggers unwanted Regular Expression.

**Comment by rugpanov** [comment]
Thank you for report. This is known issue: https://youtrack.jetbrains.com/issue/TW-57952
We're going to fix it asap.

**Comment by rugpanov** [comment]
fixed at e0f6e4914d563063ed22c1b62228aefb054a141b
