### ISSUE TITLE
Request for version of plugin where all branches are considered

### ISSUE THREAD

**Issue by Sharken03** [JetBrains/teamcity-investigations-auto-assigner#34]
In the recent commit 590c2b447f08b82bd5d604b396557758a1378c80, a change in behavior is introduced in which only builds from the default branch is considered.

For those who want the old behavior, it would be very nice to have a separate version of the plugin.
At the time where a switch can toggle between new and old behavior, a separate version of the plugin is no longer necessary.

**Comment by rugpanov** [comment]
Hi, @Sharken03 . Now you can configure this behavior with `teamcity.investigationsAutoAssigner.enableFeatureBranchesSupport=true` [build parameter](https://confluence.jetbrains.com/display/TCDL/Configuring+Build+Parameters)
or [TeamCity property](https://confluence.jetbrains.com/display/TCDL/Configuring+TeamCity+Server+Startup+Properties).

**Comment by rugpanov** [comment]
The latest version of the [plugin](https://teamcity.jetbrains.com/viewLog.html?buildId=1863266&buildTypeId=TeamCityPluginsByJetBrains_InvestigationsAutoAssigner_BuildAgainstTeamCity81x&tab=artifacts).
